"""initial baseline

Revision ID: 7f7dc8d19890
Revises: 
Create Date: 2026-05-26 13:17:26.528793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7dc8d19890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_ktc_oneqb_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_player_ktc_oneqb_values_player_redraft'))
        batch_op.create_unique_constraint('uq_player_ktc_oneqb_values_player_redraft', ['player_id', 'is_redraft'])

    with op.batch_alter_table('player_ktc_superflex_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_player_ktc_superflex_values_player_redraft'))
        batch_op.create_unique_constraint('uq_player_ktc_superflex_values_player_redraft', ['player_id', 'is_redraft'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_sleeper_player_id'), ['sleeper_player_id'], unique=False)
        batch_op.drop_column('isDevyReturningToSchool')
        batch_op.drop_column('isDevyYearDecrement')

    with op.batch_alter_table('sleeper_weekly_data', schema=None) as batch_op:
        batch_op.create_index('ix_sleeper_weekly_season_lt_week', ['season', 'league_type', 'week'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleeper_weekly_data', schema=None) as batch_op:
        batch_op.drop_index('ix_sleeper_weekly_season_lt_week')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDevyYearDecrement', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isDevyReturningToSchool', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_players_sleeper_player_id'))

    with op.batch_alter_table('player_ktc_superflex_values', schema=None) as batch_op:
        batch_op.drop_constraint('uq_player_ktc_superflex_values_player_redraft', type_='unique')
        batch_op.create_index(batch_op.f('uq_player_ktc_superflex_values_player_redraft'), ['player_id', 'is_redraft'], unique=True)

    with op.batch_alter_table('player_ktc_oneqb_values', schema=None) as batch_op:
        batch_op.drop_constraint('uq_player_ktc_oneqb_values_player_redraft', type_='unique')
        batch_op.create_index(batch_op.f('uq_player_ktc_oneqb_values_player_redraft'), ['player_id', 'is_redraft'], unique=True)

    # ### end Alembic commands ###
